main: pk.ajneb97.PlayerKits2
version: 1.18.2
name: PlayerKits2
api-version: 1.13
softdepend: [NBTAPI, Vault, PlaceholderAPI]
author: Ajneb97

commands:
  kit:
    description: Main command of PlayerKits2
    aliases: [kits,playerkits]