main: pk.ajneb97.PlayerKits2
version: 1.9.1
name: PlayerKits2
api-version: 1.13
softdepend: [Vault,PlaceholderAPI]
author: Ajneb97
folia-supported: true

commands:
  kit:
    description: Main command of PlayerKits2
    aliases: [kits,playerkits]